public class Uno {
    public static void main (String[] args) {
        int[] arr = new int[4];
        try {
            int i = arr[4];
            System.out.println("Dentro del bloque try");
        } catch (ArrayIndexOutOfBoundsException ex) {
            System.out.println("Excepci칩n atrapada en el bloque catch");
        }
        System.out.println("Fin.");
    }

}

// La salida ser치: Excepci칩n atrapada en el bloque catch y Fin

// Correcci칩n: Todo ok
